#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import os
import sys
from gstage4._patcher import RepoPatcher


def usage():
    print("Usage:")
    print("  %s <repository name> <sync uri> <location>" % (sys.argv[0]))


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == "--help":
        usage()
        sys.exit(0)

    if len(sys.argv) < 4:
        usage()
        sys.exit(1)

    sourceDir = sys.argv[0] + ".d"
    targetDirRepoName = sys.argv[1]
    syncUrl = sys.argv[2]                   # not used, only to fulfill gentoo postsync.d script spec
    targetDir = sys.argv[3]

    patcher = RepoPatcher()
    patchDirList = [os.path.join(sourceDir, x) for x in os.listdir(sourceDir)]
    patchDirList = patcher.filter_and_convert_patch_dir_list(patchDirList, targetDirRepoName)
    if len(patchDirList) > 0:
        print("Patching...")
        pendingDstDirSet = patcher.patch(targetDir, patchDirList)
        for x in patcher.warn_or_err_list:
            if x.warn_or_err:
                print("Warning: %s" % (x.msg))
            else:
                print("Error: %s" % (x.msg), file=sys.stderr)
        if any([not x.warn_or_err for x in patcher.warn_or_err_list]):
            sys.exit(1)
        patcher.generateManifest(targetDir, pendingDstDirSet)
        print("Done.")
